[package]
name = "blackspace-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
aes-gcm.workspace = true
argon2.workspace = true
base64.workspace = true
bip39.workspace = true
ciborium.workspace = true
ed25519-dalek.workspace = true
getrandom.workspace = true
getrandom_02 = { package = "getrandom", version = "0.2", features = ["js"] }
hex.workspace = true
openmls.workspace = true
openmls_basic_credential.workspace = true
openmls_rust_crypto.workspace = true
openmls_traits.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
tls_codec.workspace = true
url.workspace = true
uuid.workspace = true
zeroize.workspace = true
wasm-bindgen.workspace = true
